spring:
  datasource:
    type:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
application:
  root: target/root
  archiveRoot: target/archive-root