spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/file_system
    username: file_system_user
    password: 1q2w3e
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/changelog/master.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

application:
  root: root
  errorMessages:
    unexpectedErrorWhileCreationOperation: Unexpected error while creation operation.
    objectAlreadyExists: Object with such name already exists. Choose another one.
    clusterWithSuchNameAlreadyExists: Cluster with such name already exists.
    clusterDoesNotExists: Cluster does not exists.
    directoryExists: Directory already exists in cluster.
    directoryDoesNotExists: Directory does not exist.
    incorrectTitleLength: Title length should be between 1 and 125 characters.
    incorrectContentLength: Content length should be between 1 and 3064 characters.
    resourceNotFound: Requested resource not found.
    wrongRequestParameters: Wrong request parameters.