spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtualHost: /
  cloud:
    stream:
      bindings:
        delete-object-notification-channel:
          destination: notification.channel
          content-type: application/json
      rabbit:
        bindings:
          delete-object-notification-channel:
            producer:
              declare-exchange: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/file_system
    username: file_system_user
    password: 1q2w3e
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/changelog/master.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

application:
  root: root
  archiveRoot: archive-root
  recreateFullPath: true
  daysBeforeArchive: 30
  daysBeforeDeleteArchive: 150
  daysBeforeNotification: 140
  errorMessages:
    unexpectedErrorWhileCreationOperation: Unexpected error while creation operation.
    objectAlreadyExists: Object with such name already exists. Choose another one.
    clusterWithSuchNameAlreadyExists: Cluster with such name already exists.
    clusterDoesNotExist: Cluster does not exists.
    directoryExists: Directory already exists in cluster.
    incorrectTitleLength: Title length should be between 1 and 125 characters.
    incorrectContentLength: Content length should be between 1 and 3064 characters.
    resourceNotFound: Requested resource not found.
    wrongRequestParameters: Wrong request parameters.
    unexpectedErrorWhileReadingOperation: Unexpected error while reading operation.
    fileDoesNotExist: File does not exist.
    deletionError: Unexpected error while deleting.
    directoryDoesNotExist: Directory does not exist.
    replacingError: Error while replacing file.
    updatingError: Error while updating file.
    recreatingError: Error while recreating file.
    fileNotDeleted: File not deleted.
    parentObjectDeleted: Parent object deleted.
    directoryNotDeleted: Directory not deleted.
    clusterNotDeleted: Cluster not deleted.
    sameDirectoryReplacing: File already in this directory.

keycloak:
  auth-server-url: http://localhost:8484/auth
  realm: file_system_realm
  resource: file-sysmte-ms-client
  bearer-only: true
  security-constraints:
    - authRoles:
        - uma_authorization
      securityCollections:
        - patterns:
            - /cluster/*
            - /directory/*
            - /file/*
            - /recreate/*